### ISSUE TITLE
Can't install the module

### ISSUE THREAD

**Issue by Romano2K** [lionep/homebridge-own#4]
Hi Lionel!

We're neighbors, I live in Fort d'Issy, so I've been using your module for quite some time. :-)

For some reason, I always had to uninstall homebridge and homebridge-own and then reinstall it after each monthly or weekly upgrade of my Arch Linux server, which I think always includes an update of node.js or NPM. I've never figured why. Until now I was able to do it quickly so it was OK.

But since my last system upgrade, I can't reinstall homebridge-own.

Here is what I get:

`romain@robot ~ % sudo npm install -g homebridge-own
[sudo] Mot de passe de romain : 
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/KhaosT/node-srp.git /root/.npm/_cacache/tmp/git-clone-06561bff
npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-06561bff': Permission non accordée
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-29T14_23_02_215Z-debug.log
romain@robot ~ % sudo ls -lA /root/.npm/
total 16
drwxr-xr-x 5 root root 4096 25 nov.  20:36 _cacache
drwxr-xr-x 2 root root 4096 25 nov.  20:37 _locks
drwxr-xr-x 2 root root 4096 29 nov.  15:23 _logs
-rw-r--r-- 1 root root  171 29 nov.  15:23 anonymous-cli-metrics.json
romain@robot ~ % sudo ls -lA /root/.npm/_cacache 
total 12
drwxr-xr-x  4 root root 4096 25 nov.  20:36 content-v2
drwxr-xr-x 80 root root 4096 25 nov.  20:38 index-v5
drwxr-xr-x  2 root root 4096 29 nov.  15:23 tmp
romain@robot ~ % sudo ls -lA /root/.npm/_cacache/tmp
total 0
`
And the log:

`romain@robot ~ % sudo cat /root/.npm/_logs/2017-11-29T14_23_02_215Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-own' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose npm-session df212725c66b7cbd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-own 214ms (from cache)
8 silly pacote tag manifest for homebridge-own@latest fetched in 271ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-own@0.2.4 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/bluebird 101ms (from cache)
15 silly pacote range manifest for bluebird@^3.4.1 fetched in 120ms
16 silly resolveWithNewModule bluebird@3.5.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/hap-nodejs 132ms (from cache)
18 silly pacote range manifest for hap-nodejs@^0.3.2 fetched in 144ms
19 silly resolveWithNewModule hap-nodejs@0.3.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/lodash 149ms (from cache)
21 silly pacote range manifest for lodash@^4.14.1 fetched in 154ms
22 silly resolveWithNewModule lodash@4.17.4 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/debug 80ms (from cache)
24 silly pacote range manifest for debug@^2.2.0 fetched in 88ms
25 silly resolveWithNewModule debug@2.6.9 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/mdns 90ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/node-persist 92ms (from cache)
28 silly pacote range manifest for mdns@^2.3.2 fetched in 98ms
29 silly resolveWithNewModule mdns@2.3.4 checking installable status
30 silly pacote range manifest for node-persist@^0.0.8 fetched in 100ms
31 silly resolveWithNewModule node-persist@0.0.8 checking installable status
32 silly fetchPackageMetaData error for srp@git://github.com/KhaosT/node-srp.git Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/KhaosT/node-srp.git /root/.npm/_cacache/tmp/git-clone-06561bff
32 silly fetchPackageMetaData fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-06561bff': Permission non accordée
33 silly fetchPackageMetaData error for curve25519@git://github.com/KhaosT/node-curve25519.git Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/KhaosT/node-curve25519.git /root/.npm/_cacache/tmp/git-clone-b54dae27
33 silly fetchPackageMetaData fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-b54dae27': Permission non accordée
34 silly fetchPackageMetaData error for ed25519@git://github.com/KhaosT/ed25519.git Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/KhaosT/ed25519.git /root/.npm/_cacache/tmp/git-clone-1f1e9170
34 silly fetchPackageMetaData fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-1f1e9170': Permission non accordée
35 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/KhaosT/node-srp.git /root/.npm/_cacache/tmp/git-clone-06561bff
35 verbose stack fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-06561bff': Permission non accordée
35 verbose stack
35 verbose stack     at ChildProcess.exithandler (child_process.js:272:12)
35 verbose stack     at ChildProcess.emit (events.js:159:13)
35 verbose stack     at maybeClose (internal/child_process.js:943:16)
35 verbose stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
35 verbose stack     at Socket.emit (events.js:159:13)
35 verbose stack     at Pipe._handle.close [as _onclose] (net.js:558:12)
36 verbose cwd /home/romain
37 verbose Linux 4.13.12-1-ARCH
38 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-own"
39 verbose node v9.2.0
40 verbose npm  v5.5.1
41 error code 128
42 error Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/KhaosT/node-srp.git /root/.npm/_cacache/tmp/git-clone-06561bff
42 error fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-06561bff': Permission non accordée
43 verbose exit [ 1, true ]
`
I've tried to make a clean install of NodeJS and NPM, then homebridge, then homebridge-own on my Mac (using Brew), I have the same kind of error.

Any idea?

**Comment by Romano2K** [comment]
I'm not a Web developer and I'm using npm only for homebridge-own :-)

I just tried to uninstall nodejs and npm (with 'pacman -Rsn'), then I
manually deleted .npm and .node-gyp in /root and in ~, then reinstalled
npm, then homebridge, and I still get the same error when I "sudo npm
install -g homebridge-own".

Am I missing something? Thank you anyway for your quick response!

2017-11-29 15:43 GMT+01:00 lionep <notifications@github.com>:

**Comment by Romano2K** [comment]
Hello again!

After an update of NodeJS and NPM on my Linux server, I tried again.

I still have a permission problem, although I'm using sudo.

`% sudo npm install -g homebridge-own
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/KhaosT/ed25519.git /root/.npm/_cacache/tmp/git-clone-6023c86c
npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-6023c86c': Permission non accordée
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-30T07_07_15_469Z-debug.log`

Any idea?

**Comment by romheu** [comment]
Solved the issue by running the `npm install -g (…)` commands from a root command line (`sudo su`), instead of running them with `sudo` from a user command line.
