### ISSUE TITLE
Install failed : Command failed: /usr/bin/git clone -q git://github.com/KhaosT/ed25519.git

### ISSUE THREAD

**Issue by lboue** [lionep/homebridge-own#6]
Hello,

I am running node v10.1.0 on my Raspberry Pi 3 and I am trying to install homebridge-own but it fails. 
I don't understand why it fails on permission rights because I am running the install commande with sudo as you can see : 
```
pi@raspberrypi:~ $  sudo npm install -g --unsafe-perm homebridge-own
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/KhaosT/ed25519.git /root/.npm/_cacache/tmp/git-clone-5ea95c33
npm ERR! fatal: impossible de crï¿½er les rï¿½pertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-5ea95c33': Permission non accordï¿½e
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-30T08_49_39_016Z-debug.log
```

Could you tell me why it is trying to clone node-srp ?
```
pi@raspberrypi:~ $ sudo cat /root/.npm/_logs/2018-06-30T08_49_39_016Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-own' ]
2 info using npm@5.6.0
3 info using node@v10.1.0
4 verbose npm-session 6fb0b50200270c9c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-own 499ms (from cache)
8 silly pacote tag manifest for homebridge-own@latest fetched in 607ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-own@0.2.4 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/bluebird 145ms (from cache)
15 silly pacote range manifest for bluebird@^3.4.1 fetched in 191ms
16 silly resolveWithNewModule bluebird@3.5.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/hap-nodejs 299ms (from cache)
18 silly pacote range manifest for hap-nodejs@^0.3.2 fetched in 326ms
19 silly resolveWithNewModule hap-nodejs@0.3.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/lodash 331ms (from cache)
21 silly pacote range manifest for lodash@^4.14.1 fetched in 342ms
22 silly resolveWithNewModule lodash@4.17.10 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/mdns 225ms (from cache)
24 silly pacote range manifest for mdns@^2.3.2 fetched in 236ms
25 silly resolveWithNewModule mdns@2.4.0 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/node-persist 237ms (from cache)
27 silly pacote range manifest for node-persist@^0.0.8 fetched in 248ms
28 silly resolveWithNewModule node-persist@0.0.8 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/debug 258ms (from cache)
30 silly pacote range manifest for debug@^2.2.0 fetched in 273ms
31 silly resolveWithNewModule debug@2.6.9 checking installable status
32 silly fetchPackageMetaData error for ed25519@git://github.com/KhaosT/ed25519.git Command failed: /usr/bin/git clone -q git://github.com/KhaosT/ed25519.git /root/.npm/_cacache/tmp/git-clone-5ea95c33
32 silly fetchPackageMetaData fatal: impossible de crï¿½er les rï¿½pertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-5ea95c33': Permission non accordï¿½e
33 silly fetchPackageMetaData error for curve25519@git://github.com/KhaosT/node-curve25519.git Command failed: /usr/bin/git clone -q git://github.com/KhaosT/node-curve25519.git /root/.npm/_cacache/tmp/git-clone-73558ac9
33 silly fetchPackageMetaData fatal: impossible de crï¿½er les rï¿½pertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-73558ac9': Permission non accordï¿½e
34 silly fetchPackageMetaData error for srp@git://github.com/KhaosT/node-srp.git Command failed: /usr/bin/git clone -q git://github.com/KhaosT/node-srp.git /root/.npm/_cacache/tmp/git-clone-af26992e
34 silly fetchPackageMetaData fatal: impossible de crï¿½er les rï¿½pertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-af26992e': Permission non accordï¿½e
35 verbose stack Error: Command failed: /usr/bin/git clone -q git://github.com/KhaosT/ed25519.git /root/.npm/_cacache/tmp/git-clone-5ea95c33
35 verbose stack fatal: impossible de crï¿½er les rï¿½pertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-5ea95c33': Permission non accordï¿½e
35 verbose stack
35 verbose stack     at ChildProcess.exithandler (child_process.js:282:12)
35 verbose stack     at ChildProcess.emit (events.js:182:13)
35 verbose stack     at maybeClose (internal/child_process.js:957:16)
35 verbose stack     at Socket.stream.socket.on (internal/child_process.js:378:11)
35 verbose stack     at Socket.emit (events.js:182:13)
35 verbose stack     at Pipe._handle.close [as _onclose] (net.js:598:12)
36 verbose cwd /home/pi
37 verbose Linux 4.14.30-v7+
38 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-own"
39 verbose node v10.1.0
40 verbose npm  v5.6.0
41 error code 128
42 error Command failed: /usr/bin/git clone -q git://github.com/KhaosT/ed25519.git /root/.npm/_cacache/tmp/git-clone-5ea95c33
42 error fatal: impossible de crï¿½er les rï¿½pertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-5ea95c33': Permission non accordï¿½e
43 verbose exit [ 1, true ]
```

Regards,
Ludovic

**Comment by lionep** [comment]
It seems to be related to git://github.com/KhaosT/ed25519.git
I can't reproduce on my side. Is it still the case ?

**Comment by lboue** [comment]
Yes. I found a workaround:
```
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm bignum

> bignum@0.13.0 install /usr/lib/node_modules/bignum
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.1.0 runtime=node arch=arm platform=linux)
make : on entre dans le répertoire « /usr/lib/node_modules/bignum/build »
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
make : on quitte le répertoire « /usr/lib/node_modules/bignum/build »
+ bignum@0.13.0
updated 1 package in 25.043s

pi@raspberrypi:~ $ sudo npm install -g ed25519 --unsafe-perm

> ed25519@0.0.4 install /usr/lib/node_modules/ed25519
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/ed25519/build'
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/obj.target/ed25519.node
  COPY Release/ed25519.node
make: Leaving directory '/usr/lib/node_modules/ed25519/build'
+ ed25519@0.0.4
updated 1 package in 37.472s


pi@raspberrypi:~ $ sudo su -
root@raspberrypi:~# npm install -g homebridge-own --unsafe-perm
+ homebridge-own@0.3.1
updated 1 package in 21.82s

root@raspberrypi:~# exit 
pi@raspberrypi:~ $ ls /usr/lib/node_modules/homebridge-own/node_modules   
abbrev            balanced-match   code-point-at            delayed-stream  fstream         hawk                     jsbn                   minimatch      oauth-sign            q                signal-exit          tar-pack
ajv               bcrypt-pbkdf     combined-stream          delegates       fstream-ignore  hoek                     json-schema            minimist       object-assign         qs               sntp                 tough-cookie
ansi-regex        bignum           concat-map               detect-libc     gauge           http-signature           json-stable-stringify  mkdirp         once                  rc               srp                  tunnel-agent
aproba            bindings         console-control-strings  ecc-jsbn        getpass         inflight                 json-stringify-safe    ms             os-homedir            readable-stream  sshpk                tweetnacl
are-we-there-yet  block-stream     core-util-is             ed25519-hap     glob            inherits                 jsonify                nan            os-tmpdir             request          string-width         uid-number
asn1              bluebird         cryptiles                extend          graceful-fs     ini                      jsprim                 node-persist   osenv                 rimraf           string_decoder       util-deprecate
assert-plus       boom             curve25519               extsprintf      hap-nodejs      is-fullwidth-code-point  lodash                 node-pre-gyp   path-is-absolute      safe-buffer      stringstream         uuid
asynckit          brace-expansion  dashdash                 forever-agent   har-schema      is-typedarray            mdns                   nopt           performance-now       safer-buffer     strip-ansi           verror
aws-sign2         caseless         debug                    form-data       har-validator   isarray                  mime-db                npmlog         process-nextick-args  semver           strip-json-comments  wide-align
aws4              co               deep-extend              fs.realpath     has-unicode     isstream                 mime-types             number-is-nan  punycode              set-blocking     tar                  wrappy
pi@raspberrypi:~ $ 
```
